server:
  port: 8002
  servlet:
    context-path: /moh-api-mobile-service

spring:
  application:
    name: moh-api-mobile-service
    node:
      ip: ${MY_NODE_IP:127.0.0.1}
    pod:
      name: ${MY_POD_NAME:${spring.application.name}}
  profiles:
    active: ${PROFILE_ACTIVE:dev}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

swagger:
  server:
    dev:
      url: http://localhost:8001
    uat:
      url: https://owa.apb.com.la:442
    prd:
      url: https://apb.services.pro

app:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    max-age: 3600